### ISSUE TITLE
UI Fixes

### ISSUE THREAD

**Issue by citizenfish** [nautoguide/locus_open#268]
1) Misalignment of boxes on front page (Safari)

<img width="1132" alt="Screenshot 2021-09-14 at 13 02 12" src="https://user-images.githubusercontent.com/10531204/133254064-58454c29-3cdb-4e06-b7b1-84ce000a9640.png">

2) Add zoom controls to front page map

3) Add space after < on distance display

<img width="631" alt="Screenshot 2021-09-14 at 13 02 51" src="https://user-images.githubusercontent.com/10531204/133254155-38f6bb9a-3bc4-4ec7-bdb4-ef10c06fda5f.png">

4) Map icons on edge of map in detail view. Needs some padding to make these fully visible

<img width="639" alt="Screenshot 2021-09-14 at 13 03 37" src="https://user-images.githubusercontent.com/10531204/133254259-fa22a5ed-2573-49ba-90ec-e170b2197f95.png">

5) Add text title to pages so that browser tabs are properly identifiable

**Comment by richardjr** [comment]
All fixed in latest release
